//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snet.Windows.KMSim {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Snet.Windows.KMSim.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [ Shunnet.top ] Windows 键鼠模拟工具 的本地化字符串。
        /// </summary>
        internal static string SystemTitle {
            get {
                return ResourceManager.GetString("SystemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不存在 的本地化字符串。
        /// </summary>
        internal static string 不存在 {
            get {
                return ResourceManager.GetString("不存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持的图像文件格式 的本地化字符串。
        /// </summary>
        internal static string 不支持的图像文件格式 {
            get {
                return ResourceManager.GetString("不支持的图像文件格式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string 保存 {
            get {
                return ResourceManager.GetString("保存", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存图片 的本地化字符串。
        /// </summary>
        internal static string 保存图片 {
            get {
                return ResourceManager.GetString("保存图片", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功 的本地化字符串。
        /// </summary>
        internal static string 保存成功 {
            get {
                return ResourceManager.GetString("保存成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        internal static string 信息 {
            get {
                return ResourceManager.GetString("信息", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 F11 的本地化字符串。
        /// </summary>
        internal static string 停止 {
            get {
                return ResourceManager.GetString("停止", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string 关于 {
            get {
                return ResourceManager.GetString("关于", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string 关闭 {
            get {
                return ResourceManager.GetString("关闭", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭成功 的本地化字符串。
        /// </summary>
        internal static string 关闭成功 {
            get {
                return ResourceManager.GetString("关闭成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出错 的本地化字符串。
        /// </summary>
        internal static string 出错 {
            get {
                return ResourceManager.GetString("出错", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原始数据 的本地化字符串。
        /// </summary>
        internal static string 原始数据 {
            get {
                return ResourceManager.GetString("原始数据", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令 的本地化字符串。
        /// </summary>
        internal static string 命令 {
            get {
                return ResourceManager.GetString("命令", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ Shunnet.top ] Windows 键鼠模拟工具 - 命令查找窗口 的本地化字符串。
        /// </summary>
        internal static string 命令查找窗口 {
            get {
                return ResourceManager.GetString("命令查找窗口", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像保存失败 的本地化字符串。
        /// </summary>
        internal static string 图像保存失败 {
            get {
                return ResourceManager.GetString("图像保存失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制图片 的本地化字符串。
        /// </summary>
        internal static string 复制图片 {
            get {
                return ResourceManager.GetString("复制图片", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已保存至 的本地化字符串。
        /// </summary>
        internal static string 已保存至 {
            get {
                return ResourceManager.GetString("已保存至", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已取消 的本地化字符串。
        /// </summary>
        internal static string 已取消 {
            get {
                return ResourceManager.GetString("已取消", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已取消操作 的本地化字符串。
        /// </summary>
        internal static string 已取消操作 {
            get {
                return ResourceManager.GetString("已取消操作", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已存在 的本地化字符串。
        /// </summary>
        internal static string 已存在 {
            get {
                return ResourceManager.GetString("已存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助 的本地化字符串。
        /// </summary>
        internal static string 帮助 {
            get {
                return ResourceManager.GetString("帮助", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始 F10 的本地化字符串。
        /// </summary>
        internal static string 开始 {
            get {
                return ResourceManager.GetString("开始", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常 的本地化字符串。
        /// </summary>
        internal static string 异常 {
            get {
                return ResourceManager.GetString("异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string 成功 {
            get {
                return ResourceManager.GetString("成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功保存至 的本地化字符串。
        /// </summary>
        internal static string 成功保存至 {
            get {
                return ResourceManager.GetString("成功保存至", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        internal static string 打开 {
            get {
                return ResourceManager.GetString("打开", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开成功 的本地化字符串。
        /// </summary>
        internal static string 打开成功 {
            get {
                return ResourceManager.GetString("打开成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行 的本地化字符串。
        /// </summary>
        internal static string 执行 {
            get {
                return ResourceManager.GetString("执行", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        internal static string 描述 {
            get {
                return ResourceManager.GetString("描述", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string 提示 {
            get {
                return ResourceManager.GetString("提示", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        internal static string 文件 {
            get {
                return ResourceManager.GetString("文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建 的本地化字符串。
        /// </summary>
        internal static string 新建 {
            get {
                return ResourceManager.GetString("新建", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建成功 的本地化字符串。
        /// </summary>
        internal static string 新建成功 {
            get {
                return ResourceManager.GetString("新建成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方法 的本地化字符串。
        /// </summary>
        internal static string 方法 {
            get {
                return ResourceManager.GetString("方法", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法将 的本地化字符串。
        /// </summary>
        internal static string 无法将 {
            get {
                return ResourceManager.GetString("无法将", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到可匹配的重载方法 的本地化字符串。
        /// </summary>
        internal static string 未找到可匹配的重载方法 {
            get {
                return ResourceManager.GetString("未找到可匹配的重载方法", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查找 的本地化字符串。
        /// </summary>
        internal static string 查找 {
            get {
                return ResourceManager.GetString("查找", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程已停止 的本地化字符串。
        /// </summary>
        internal static string 流程已停止 {
            get {
                return ResourceManager.GetString("流程已停止", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程异常 的本地化字符串。
        /// </summary>
        internal static string 流程异常 {
            get {
                return ResourceManager.GetString("流程异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        internal static string 清空 {
            get {
                return ResourceManager.GetString("清空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 留言 的本地化字符串。
        /// </summary>
        internal static string 留言 {
            get {
                return ResourceManager.GetString("留言", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监控 的本地化字符串。
        /// </summary>
        internal static string 监控 {
            get {
                return ResourceManager.GetString("监控", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线条操作 的本地化字符串。
        /// </summary>
        internal static string 线条操作 {
            get {
                return ResourceManager.GetString("线条操作", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详情 的本地化字符串。
        /// </summary>
        internal static string 详情 {
            get {
                return ResourceManager.GetString("详情", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择文件夹 的本地化字符串。
        /// </summary>
        internal static string 请选择文件夹 {
            get {
                return ResourceManager.GetString("请选择文件夹", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调整 的本地化字符串。
        /// </summary>
        internal static string 调整 {
            get {
                return ResourceManager.GetString("调整", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换为 的本地化字符串。
        /// </summary>
        internal static string 转换为 {
            get {
                return ResourceManager.GetString("转换为", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        internal static string 返回 {
            get {
                return ResourceManager.GetString("返回", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string 退出 {
            get {
                return ResourceManager.GetString("退出", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 逻辑 的本地化字符串。
        /// </summary>
        internal static string 逻辑 {
            get {
                return ResourceManager.GetString("逻辑", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        internal static string 重置 {
            get {
                return ResourceManager.GetString("重置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重试 F12 的本地化字符串。
        /// </summary>
        internal static string 重试 {
            get {
                return ResourceManager.GetString("重试", resourceCulture);
            }
        }
    }
}
